/**
 * This file was genuinely, entirely generated by Claude Code.
 */

import type { CvLocaleData, CvUiConfig } from '../types/config';

const HEX_COLOR = /^#[0-9a-f]{3,8}$/i;
const CONTENT_LIGHT = '#24272b';
const CONTENT_DARK = '#fffffa';
const SURFACE_LIGHT = CONTENT_DARK;
const SURFACE_DARK = CONTENT_LIGHT;

const resolveAccent = (value: string | undefined, fallback: string) =>
  value && HEX_COLOR.test(value) ? value : fallback;

export const toFaviconSvg = (locale: CvLocaleData, ui?: CvUiConfig): string => {
  const first = locale.firstName.charAt(0).toUpperCase();
  const last = locale.lastName.charAt(0).toUpperCase();
  const accentLight = resolveAccent(ui?.accentColor, CONTENT_LIGHT);
  const accentDark = resolveAccent(ui?.accentColorDark, CONTENT_DARK);

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<style>
.surface{fill:${SURFACE_LIGHT}}
.content{fill:${CONTENT_LIGHT}}
.accent{fill:${accentLight}}
@media (prefers-color-scheme: dark){.surface{fill:${SURFACE_DARK}}.content{fill:${CONTENT_DARK}}.accent{fill:${accentDark}}}
</style>
<polygon class="surface" points="16,1 31,16 16,31 1,16"/>
<text x="16" y="21" text-anchor="middle" font-family="system-ui, sans-serif" font-weight="700" font-size="14"><tspan class="content">${first}</tspan><tspan class="accent">${last}</tspan></text>
</svg>`;
};

export const toFaviconDataUri = (
  locale: CvLocaleData,
  ui?: CvUiConfig,
): string =>
  `data:image/svg+xml,${encodeURIComponent(toFaviconSvg(locale, ui))}`;
